export const penalties = [
  {
    label: "Failure to issue an electronic receipt or invoice",
    value: "EFRIS_01",
    comparative: false,
    currencyPoints: 50,
    maxAmount: 500000,
    category: "EFRIS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Late submission of income tax returns",
    value: "DTS_01",
    comparative: true,
    currencyPoints: 100,
    maxAmount: 1000000,
    category: "DTS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Failure to report cross-border transactions",
    value: "International_Tax_01",
    comparative: false,
    currencyPoints: 200,
    maxAmount: 2000000,
    category: "International Tax",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Non-compliance with electronic stamp requirements",
    value: "EFRIS_02",
    comparative: true,
    currencyPoints: 150,
    maxAmount: 1500000,
    category: "EFRIS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Incorrect tax declaration",
    value: "DTS_02",
    comparative: true,
    currencyPoints: 120,
    maxAmount: 1200000,
    category: "DTS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Undervaluation of goods for customs purposes",
    value: "International_Tax_02",
    comparative: false,
    currencyPoints: 250,
    maxAmount: 2500000,
    category: "International Tax",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Failure to deduct or remit PAYE",
    value: "EFRIS_03",
    comparative: false,
    currencyPoints: 75,
    maxAmount: 750000,
    category: "EFRIS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Failure to withhold or remit withholding tax",
    value: "DTS_03",
    comparative: true,
    currencyPoints: 85,
    maxAmount: 850000,
    category: "DTS",
    doubleTax: true,
    dailyFine: false,
  },
  {
    label: "Non-disclosure of foreign income",
    value: "International_Tax_03",
    comparative: false,
    currencyPoints: 300,
    maxAmount: 3000000,
    category: "International Tax",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "General non-compliance with EFRIS regulations",
    value: "EFRIS_04",
    comparative: false,
    currencyPoints: 60,
    maxAmount: 600000,
    category: "EFRIS",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Penal Tax for Failing to Maintain Proper Records",
    value: "PT_01",
    comparative: false, // No comparison needed, straightforward doubling
    category: "General",
    currencyPoints: 10,
    doubleTax: true, // Penalty is double the tax payable
    dailyFine: false,
  },
  {
    label: "Penalty for Failing to Apply for Registration",
    value: "REG_01",
    comparative: true, // Choose higher of doubleTax amount or maxAmount
    currencyPoints: 50, // Used to calculate maxAmount or fixed amount
    category: "Registration",
    doubleTax: true,
    maxAmount: 1250000,
    dailyFine: false,
  },
  {
    label: "Failing to Furnish a Tax Return",
    value: "FT_01",
    comparative: false, // Officer can edit downwards from maxAmount
    currencyPoints: 25, // Maximum currency points
    maxAmount: 750000,
    category: "General",
    doubleTax: false,
    dailyFine: false,
  },
  {
    label: "Offences Related to Automatic Exchange of Information",
    value: "AEI_01",
    dailyFine: true, // Indicates a daily fine applies
    currencyPoints: 2500, // Daily fine amount in currency points
    category: "EFRIS",
    doubleTax: false, // Not relevant for daily fines
    comparative: false, // Not directly relevant, but could imply no comparison needed
    dailyMaxAmount: 62500000,
  },
];
